"""create added time column in cart (step 03.1)

Revision ID: 55346afd64bc
Revises: d9dc7d264ce5
Create Date: 2023-06-22 02:13:24.046543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55346afd64bc'
down_revision = 'd9dc7d264ce5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shopping_cart_item', sa.Column('added_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shopping_cart_item', 'added_at')
    # ### end Alembic commands ###
