"""create product db (step 02)

Revision ID: c644f4e48074
Revises: 9e018bb447f6
Create Date: 2023-06-22 00:11:17.885079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c644f4e48074'
down_revision = '9e018bb447f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('product_image', sa.String(), nullable=True),
    sa.Column('qty_in_stock', sa.Integer(), nullable=False),
    sa.Column('price', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    # ### end Alembic commands ###
